import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import { NavBar } from "../components/NavBar";

const pubicSans = Public_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pubicSans.className}>
        <div className="bg-white flex items-center w-full flex-col">
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
